jsfwf-web/src/main/java/jsfwf/controller/LoginController.java
package jsfwf.controller;

import org.jboss.logging.Logger;
import jsfwf.data.UserRepository;
import jsfwf.model.TestData;
import jsfwf.model.User;
import jsfwf.util.FacesUtil;

import javax.annotation.PostConstruct;
import javax.enterprise.context.ApplicationScoped;
import javax.faces.application.FacesMessage;
import javax.faces.context.ExternalContext;
import javax.faces.context.FacesContext;
import javax.faces.event.AjaxBehaviorEvent;
import javax.inject.Inject;
import javax.inject.Named;
import javax.servlet.ServletException;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import java.io.IOException;
import java.io.Serializable;

@Named("loginController")
@ApplicationScoped
public class LoginController implements Serializable {

    private static final long serialVersionUID = -2879890213L;

    private static final Logger LOGGER = Logger.getLogger(LoginController.class);

    private static final String HOME_PAGE_REDIRECT = "index.xhtml?faces-redirect=true";

    private static final String S_CURRENT_USER = "currentUser";
    private static final String S_EDIT_USER = "editUser";

    @Inject
    private FacesUtil facesUtil;
    
    @Inject
    private UserRepository userRepository;
    
    @Inject
    TestData testData;
    
    @PostConstruct
    public void postConstruct() {
        LOGGER.debug("@PostConstruct");

        testData.createData();
        
        if (getEdiUser() == null) {
            LOGGER.debug("  PostC, creating ediUser");
            setEdiUser(new User());
        }
    }

    public User getEdiUser() { return facesUtil.getSessionUser(S_EDIT_USER); }
    public void setEdiUser(User user) { facesUtil.setSessionUser(S_EDIT_USER, user); }

    public void login(AjaxBehaviorEvent evt) {   // for experiments with Ajax 
        login();
    }
    
    public String login() {

        LOGGER.info("## login()");
        User eu = getEdiUser();
        LOGGER.debug("login: name=" + eu.getLoginName() + " password=" + eu.getPassword());

        FacesContext context = FacesContext.getCurrentInstance();
        ExternalContext externalContext = context.getExternalContext();
        HttpServletRequest request = (HttpServletRequest) externalContext.getRequest();

        HttpServletResponse response;
        try {
            request.login(eu.getLoginName(), eu.getPassword());
            response = (HttpServletResponse) externalContext.getResponse();
            request.authenticate(response);
            LOGGER.debug("login survived");
        }
        catch (ServletException | IOException e) {
            LOGGER.info("## login failed");
            context.addMessage("Ajaj", new FacesMessage(FacesMessage.SEVERITY_WARN, "Login failed", e.toString()));
            return null;
        }

        // Login successful, set members, log
        facesUtil.logRequest(request, true);
        if (response != null) {
            facesUtil.logResponse(response);
        }
        
        User user = userRepository.findByLoginName(eu.getLoginName());
        setCurrentUser(user);
        LOGGER.debug("isLoggedIn: " + getCurrentUser() + " isAdmin: " + isAdminLoggedIn());
        LOGGER.debug("login: OK, redirecting to " + HOME_PAGE_REDIRECT);
        
        return HOME_PAGE_REDIRECT;
    }
        
    public String logout() {
        LOGGER.debug("logout");
                
        FacesContext context = FacesContext.getCurrentInstance();
        ExternalContext externalContext = context.getExternalContext();
        
        HttpServletRequest request = (HttpServletRequest) externalContext.getRequest();
        if (request != null) {
            try {
                request.logout();
                LOGGER.info("logout successful");
            } catch (ServletException e) {
                LOGGER.info("logout() error");
            }
            facesUtil.logRequest(request, false);
        }
        setCurrentUser(null);
        
        return HOME_PAGE_REDIRECT;
    }

    public String ifLoggedInForwardHome() {
        return isLoggedIn() ? HOME_PAGE_REDIRECT : null;
    }
    public boolean isLoggedIn() {
        return getCurrentUser() != null;
    }

    public boolean isAdminLoggedIn() {
        User currentUser = facesUtil.getSessionUser(S_CURRENT_USER);
        return currentUser != null && currentUser.hasAdminRole();
    }

    User getCurrentUser() {
        return facesUtil.getSessionUser(S_CURRENT_USER);
    }
    public void setCurrentUser(User user) {
        facesUtil.setSessionUser(S_CURRENT_USER, user);
    }

    // For JSF
    public String getCurrentUserName() {
        LOGGER.trace("getCurrentUserName()");
        User cu = getCurrentUser();
        return (cu != null ? cu.getLoginName() : "");
    }
    // Since the current user and 'logout' are in a combo box whose value can change
    public void setCurrentUserName(String name) {
        LOGGER.debug("dummy setCurrentUserName() name=" + name);
    }
}

jsfwf-web/src/main/java/jsfwf/util/LanguageBean.java
package jsfwf.util;

import org.jboss.logging.Logger;

import javax.faces.bean.ManagedBean;
import javax.faces.bean.SessionScoped;
import javax.faces.context.FacesContext;
import javax.faces.event.ValueChangeEvent;
import java.io.Serializable;
import java.util.LinkedHashMap;
import java.util.Locale;
import java.util.Map;

// Taken from an example by MkYong.
// Supports a component to change languages on the fly.
//
@ManagedBean(name="language")
@SessionScoped
public class LanguageBean implements Serializable{

    private static final long serialVersionUID = 1L;

    private static final Logger LOGGER = Logger.getLogger(LanguageBean.class); 
	
	private String localeCode = "hu";
	
	private static Map<String,Object> countries;
	static{
		countries = new LinkedHashMap<>();
		countries.put("English", Locale.ENGLISH);
		countries.put("Magyar", new Locale("hu"));
	}

	public Map<String, Object> getCountriesInMap() {
		return countries;
	}

	
	public String getLocaleCode() { return localeCode;	}
	public void setLocaleCode(String localeCode) { this.localeCode = localeCode; }


	public void countryLocaleCodeChanged(ValueChangeEvent e){
	
	    LOGGER.debug("countryLocaleCodeChanged()");
                
		String newLocaleValue = e.getNewValue().toString();
		
		// loop a map to compare the locale code
        for (Map.Entry<String, Object> entry : countries.entrySet()) {

            LOGGER.debug("  entry:" + entry.getValue().toString() + " new: " + newLocaleValue);
        	if (entry.getValue().toString().equals(newLocaleValue)){
        	
        	    Locale loc = ((Locale)entry.getValue());
        	    localeCode = loc.getLanguage();
        		FacesContext.getCurrentInstance().getViewRoot().setLocale(loc);
        	}
        }
	}
}

jsfwf-web/src/main/webapp/template/commonContent.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" 
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"   
      xmlns:ui="http://java.sun.com/jsf/facelets" >

    <body>
	    <ui:composition>
	
			<h1>This is default content</h1>
				
	    </ui:composition>
    </body>
</html>

jsfwf-web/src/main/webapp/template/commonFooter.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" 
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:ui="http://java.sun.com/jsf/facelets" >

    <body>
	    <ui:composition>

            <hr/>
            <h:outputText value="#{msg['gen.footerText']}" />
				
	    </ui:composition>
    </body>
</html>

jsfwf-web/src/main/webapp/template/commonHeader.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" 
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:ui="http://java.sun.com/jsf/facelets">

    <body>
    
      <ui:composition>
        
        <table id="headerTable">
          <tr>
            <td>
              <ul id="menu">
                <li> <h:link value="#{msg['main.main']}" outcome="/index.xhtml"> </h:link> </li>
                
                <li> <h:link value="#{msg['main.requests']}" outcome="/pages/user/requests.xhtml"
                             rendered="#{loginController.loggedIn}"> </h:link> </li>
                
                <li> <h:link value="#{msg['main.admin']}" outcome="/pages/admin/admin.xhtml"
                             rendered="#{loginController.adminLoggedIn}"> </h:link> </li>

                <li> <h:link value="#{msg['main.events']}" outcome="/pages/admin/events.xhtml"
                             rendered="#{loginController.adminLoggedIn}"> </h:link> </li>
                
                <li> <h:link value="#{msg['main.users']}" outcome="/pages/admin/users.xhtml"
                             rendered="#{loginController.adminLoggedIn}"> </h:link> </li>

                <li> <h:link value="#{msg['main.login']}" outcome="/login.xhtml"
                             rendered="#{!loginController.loggedIn}"> </h:link> </li>
              </ul>
            </td>
            <td style="padding: 4px 4px 2px 10px">
              <h:form id="loginComboForm" rendered="#{loginController.loggedIn}">
                <h:selectOneMenu value="#{loginController.currentUserName}"
                                 onchange="submit()"
                                 valueChangeListener="#{loginController.logout}">
                  <f:selectItem itemValue="0" itemLabel="#{loginController.currentUserName}" />
                  <f:selectItem itemValue="1" itemLabel="#{msg['main.logout']}" />
                </h:selectOneMenu>
              </h:form>
            </td>
            <td>
              <h:form id="langForm">
                <h:selectOneMenu value="#{language.localeCode}" onchange="submit()"
                                 valueChangeListener="#{language.countryLocaleCodeChanged}">
                  <f:selectItems value="#{language.countriesInMap}" />
                </h:selectOneMenu>
              </h:form>
            </td>
          </tr>
        </table>
      
        <hr/>
        
      </ui:composition>

    </body>
</html>

jsfwf-web/src/main/webapp/template/commonLayout.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:ui="http://java.sun.com/jsf/facelets"
>

<f:view locale="#{language.localeCode}">

<h:head>
  <h:outputStylesheet name="reset.css" library="css" />
  <h:outputStylesheet name="style.css" library="css" />
</h:head>

<h:body>

  <div id="page">

    <div id="header">
      <ui:insert name="header" >
        <ui:include src="/template/commonHeader.xhtml" />
      </ui:insert>
    </div>

    <div id="content">
      <ui:insert name="content" >
        <ui:include src="/template/commonContent.xhtml" />
      </ui:insert>
    </div>

    <div id="footer">
      <ui:insert name="footer" >
        <ui:include src="/template/commonFooter.xhtml" />
      </ui:insert>
    </div>

  </div>

</h:body>
</f:view>
</html>